# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/freebsd-10.0"
  # VirtualBox shared folder doesn't work with OpenBSDs so we'll use a NFS share
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  # Install Python via shell provisioner
  config.vm.provision "shell", inline: "yes | pkg install python"
  # Now do further provisioning via Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
