# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "tmatilai/openbsd-5.5"
  # VirtualBox shared folder doesn't work with OpenBSDs so we'll use a NFS share
  config.vm.network "private_network", ip: "192.168.50.5"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  # Install Python via shell provisioner
  config.vm.provision "shell", inline: "export PKG_PATH=ftp://129.128.5.191/pub/OpenBSD/5.5/packages/amd64/; pkg_add python-2.7.6p0"
  # Now do further provisioning via Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
