# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
IP_ADDRESS = "192.168.70.52"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty64"
  config.vm.network :private_network, ip: IP_ADDRESS
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
